#ifndef _INFRA_CONFIG_H_
#define _INFRA_CONFIG_H_

#define PLATFORM_HAS_STDINT
#define PLATFORM_HAS_DYNMEM
#define PLATFORM_HAS_OS
#define INFRA_SHA256
#define DEV_SIGN
#define DEVICE_MODEL_CLASSIC
#define ATM_ENABLED
#define AT_PARSER_ENABLED
#define AT_HAL_NONE

#endif
